version: '3'
services:
  json-server:
    build:
      context: ./mockserver
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: mockserver
  superheroes:
    build:
      context: ./superheroes
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: superheroes