version: '3'
services:
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w db.json
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/data
    restart: always
  superheroes:
    build:
      context: ./superheroes
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: superheroes